// Code generated by cmd/webconst from the server's own rules. DO NOT EDIT.
// `make gen` rewrites it; CI fails when it is stale.

import type { components } from "./schema";

type OperationType = components["schemas"]["OperationType"];
type InstrumentType = components["schemas"]["InstrumentType"];

/** The oldest date an operation may carry: a typo guard, not a valuation limit. */
export const EARLIEST_OPERATION_DATE = "1900-01-01";

/** The largest amount, in minor units, the server stores. */
export const MAX_AMOUNT_MINOR = 1_000_000_000_000_000;

/** A currency code's shape. */
export const CURRENCY_CODE = /^[A-Z]{3}$/;

/** A username's shape. */
export const USERNAME = /^[a-z0-9_]{3,32}$/;

/** The shortest password the server takes. */
export const MIN_PASSWORD_LENGTH = 8;

/** Which kinds of paper a hand entry of each type may name (decision Р-17); a type not listed may name any. */
export const KINDS_FOR: Partial<Record<OperationType, readonly InstrumentType[]>> = {
  amortization: ["bond", "custom"],
  buy: ["share", "etf", "bond", "crypto", "metal", "custom"],
  coupon: ["bond", "custom"],
  dividend: ["share", "etf", "custom"],
  redemption: ["bond", "etf", "custom"],
  sell: ["share", "etf", "bond", "crypto", "metal", "custom"],
};
