/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSetupStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["performSetup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMembers"];
        put?: never;
        post: operations["createMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteMember"];
        options?: never;
        head?: never;
        patch: operations["updateMember"];
        trace?: never;
    };
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAccounts"];
        put?: never;
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Archives the account (soft delete). */
        delete: operations["archiveAccount"];
        options?: never;
        head?: never;
        patch: operations["updateAccount"];
        trace?: never;
    };
    "/api/v1/accounts/{accountId}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Sets a manual balance mark for a date (upsert per account+date). */
        put: operations["setAccountBalance"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchInstruments"];
        put?: never;
        post: operations["createInstrument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instruments/{instrumentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateInstrument"];
        trace?: never;
    };
    "/api/v1/accounts/{accountId}/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAccountOperations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Creates a linked transfer_out/transfer_in pair moving instrument quantity between accounts with FIFO cost-basis carryover. */
        post: operations["createTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/{operationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Deletes the operation (whole pair for transfers). Rejected if the remaining journal becomes inconsistent (oversell). */
        delete: operations["deleteOperation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{accountId}/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAccountPositions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
        };
        SetupStatus: {
            setup_needed: boolean;
        };
        SetupRequest: {
            space_name: string;
            username: string;
            display_name: string;
            password: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        UserInfo: {
            /** Format: uuid */
            id: string;
            username: string;
            display_name: string;
        };
        SessionInfo: {
            user: components["schemas"]["UserInfo"];
            role: components["schemas"]["Role"];
            /** Format: uuid */
            space_id: string;
            space_name: string;
        };
        /** @enum {string} */
        Role: "owner" | "editor" | "viewer";
        MemberInfo: {
            /** Format: uuid */
            id: string;
            username: string;
            display_name: string;
            role: components["schemas"]["Role"];
        };
        CreateMemberRequest: {
            username: string;
            display_name: string;
            password: string;
            role: components["schemas"]["Role"];
        };
        UpdateMemberRequest: {
            role: components["schemas"]["Role"];
        };
        /** @enum {string} */
        AccountType: "brokerage" | "checking" | "savings" | "deposit" | "credit_card" | "loan" | "cash";
        /** @enum {string} */
        AccountStatus: "active" | "archived";
        AccountWithBalance: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            owner_user_id?: string | null;
            name: string;
            type: components["schemas"]["AccountType"];
            currency: string;
            institution: string;
            status: components["schemas"]["AccountStatus"];
            /** Format: date-time */
            created_at: string;
            balance?: components["schemas"]["BalancePoint"];
        };
        BalancePoint: {
            /** @description Date YYYY-MM-DD */
            as_of: string;
            /** Format: int64 */
            amount_minor: number;
        };
        CreateAccountRequest: {
            name: string;
            type: components["schemas"]["AccountType"];
            /** @description ISO-4217, e.g. RUB */
            currency: string;
            institution?: string;
            /** Format: uuid */
            owner_user_id?: string | null;
        };
        UpdateAccountRequest: {
            name?: string;
            institution?: string;
            /** Format: uuid */
            owner_user_id?: string | null;
            status?: components["schemas"]["AccountStatus"];
        };
        SetBalanceRequest: {
            /** @description Date YYYY-MM-DD */
            as_of: string;
            /** Format: int64 */
            amount_minor: number;
        };
        CurrencyTotal: {
            currency: string;
            /** Format: int64 */
            assets_minor: number;
            /**
             * Format: int64
             * @description Negative or zero
             */
            liabilities_minor: number;
            /** Format: int64 */
            net_minor: number;
        };
        Summary: {
            totals: components["schemas"]["CurrencyTotal"][];
        };
        /** @enum {string} */
        InstrumentType: "share" | "bond" | "etf" | "currency" | "crypto" | "metal" | "custom";
        Instrument: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["InstrumentType"];
            name: string;
            ticker: string;
            isin: string;
            figi: string;
            currency: string;
            /** Format: int64 */
            face_value_minor?: number | null;
            face_currency?: string | null;
            frozen: boolean;
        };
        CreateInstrumentRequest: {
            type: components["schemas"]["InstrumentType"];
            name: string;
            ticker?: string;
            isin?: string;
            figi?: string;
            currency: string;
            /** Format: int64 */
            face_value_minor?: number | null;
            face_currency?: string | null;
        };
        UpdateInstrumentRequest: {
            name?: string;
            ticker?: string;
            isin?: string;
            figi?: string;
            frozen?: boolean;
            /** Format: int64 */
            face_value_minor?: number | null;
            face_currency?: string | null;
        };
        /** @enum {string} */
        OperationType: "buy" | "sell" | "deposit" | "withdrawal" | "dividend" | "coupon" | "amortization" | "fee" | "tax" | "transfer_in" | "transfer_out" | "split" | "interest" | "conversion";
        Operation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            account_id: string;
            /** Format: uuid */
            instrument_id?: string | null;
            type: components["schemas"]["OperationType"];
            /** @description Date YYYY-MM-DD */
            occurred_on: string;
            /** @description Date YYYY-MM-DD */
            settled_on?: string | null;
            /** @description Decimal as string */
            quantity?: string | null;
            /** @description Decimal as string */
            price?: string | null;
            /** Format: int64 */
            amount_minor: number;
            currency: string;
            /** Format: int64 */
            fee_minor: number;
            note: string;
            /** Format: uuid */
            transfer_group_id?: string | null;
            /** @description Decimal as string */
            split_ratio?: string | null;
            source: string;
            /** Format: date-time */
            created_at: string;
        };
        CreateOperationRequest: {
            /** Format: uuid */
            account_id: string;
            /** Format: uuid */
            instrument_id?: string | null;
            type: components["schemas"]["OperationType"];
            /** @description Date YYYY-MM-DD */
            occurred_on: string;
            settled_on?: string | null;
            /** @description Decimal as string */
            quantity?: string | null;
            /** @description Decimal as string */
            price?: string | null;
            /** Format: int64 */
            amount_minor: number;
            currency: string;
            /** Format: int64 */
            fee_minor?: number;
            note?: string;
            /** @description Decimal as string */
            split_ratio?: string | null;
        };
        TransferRequest: {
            /** Format: uuid */
            from_account_id: string;
            /** Format: uuid */
            to_account_id: string;
            /** Format: uuid */
            instrument_id: string;
            /** @description Decimal as string */
            quantity: string;
            /** @description Date YYYY-MM-DD */
            occurred_on: string;
            /**
             * Format: int64
             * @description Cost basis override; default is FIFO carryover from the source account
             */
            cost_minor?: number | null;
            note?: string;
        };
        TransferResponse: {
            out: components["schemas"]["Operation"];
            in: components["schemas"]["Operation"];
        };
        Position: {
            instrument: components["schemas"]["Instrument"];
            /** @description Decimal as string */
            quantity: string;
            /** Format: int64 */
            cost_minor: number;
            /** Format: int64 */
            realized_pnl_minor: number;
            /** Format: int64 */
            income_minor: number;
            /** Format: int64 */
            fees_minor: number;
            currency: string;
        };
        PositionsResponse: {
            positions: components["schemas"]["Position"][];
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSetupStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Setup status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatus"];
                };
            };
        };
    };
    performSetup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Instance initialized, caller signed in */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Family members */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberInfo"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    createMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMemberRequest"];
            };
        };
        responses: {
            /** @description Member created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberInfo"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    deleteMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    updateMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberRequest"];
            };
        };
        responses: {
            /** @description Updated member */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberInfo"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accounts with latest balances */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountWithBalance"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description Created account */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountWithBalance"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    archiveAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    updateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAccountRequest"];
            };
        };
        responses: {
            /** @description Updated account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountWithBalance"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    setAccountBalance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetBalanceRequest"];
            };
        };
        responses: {
            /** @description Account with the new latest balance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountWithBalance"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Per-currency totals over active accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    searchInstruments: {
        parameters: {
            query?: {
                query?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching instruments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instrument"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    createInstrument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInstrumentRequest"];
            };
        };
        responses: {
            /** @description Created instrument */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instrument"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    updateInstrument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrumentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateInstrumentRequest"];
            };
        };
        responses: {
            /** @description Updated instrument */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instrument"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listAccountOperations: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account operations, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    createOperation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOperationRequest"];
            };
        };
        responses: {
            /** @description Created operation */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    createTransfer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferRequest"];
            };
        };
        responses: {
            /** @description Created pair */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransferResponse"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    deleteOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listAccountPositions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Open positions computed from the journal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionsResponse"];
                };
            };
            401: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
}
