// Command webconst writes the server's rules the web forms check before Save
// into web/src/api/constants.gen.ts, so the two cannot drift apart (plan item
// 2.7): `make gen` runs it, and CI fails when the file is stale.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"log"
	"os"
	"slices"
	"strconv"
	"strings"
	"time"

	"babki.my/babki/internal/family"
	"babki.my/babki/internal/operation"
	"babki.my/babki/internal/platform/currency"
	"babki.my/babki/internal/platform/dates"
	"babki.my/babki/internal/platform/money"
)

func main() {
	out := flag.String("o", "web/src/api/constants.gen.ts", "file to write")
	flag.Parse()
	if err := os.WriteFile(*out, render(), 0o644); err != nil {
		log.Fatal(err)
	}
}

// render is the generated file.
func render() []byte {
	var b bytes.Buffer
	b.WriteString(`// Code generated by cmd/webconst from the server's own rules. DO NOT EDIT.
// ` + "`make gen`" + ` rewrites it; CI fails when it is stale.

import type { components } from "./schema";

type OperationType = components["schemas"]["OperationType"];
type InstrumentType = components["schemas"]["InstrumentType"];

`)
	fmt.Fprintf(&b, "/** The oldest date an operation may carry: a typo guard, not a valuation limit. */\n")
	fmt.Fprintf(&b, "export const EARLIEST_OPERATION_DATE = %q;\n\n", dates.EarliestRecordable().Format(time.DateOnly))
	fmt.Fprintf(&b, "/** The largest amount, in minor units, the server stores. */\n")
	fmt.Fprintf(&b, "export const MAX_AMOUNT_MINOR = %s;\n\n", grouped(money.MaxAmountMinor))
	fmt.Fprintf(&b, "/** A currency code's shape. */\n")
	fmt.Fprintf(&b, "export const CURRENCY_CODE = /%s/;\n\n", currency.Pattern)
	fmt.Fprintf(&b, "/** A username's shape. */\n")
	fmt.Fprintf(&b, "export const USERNAME = /%s/;\n\n", family.UsernamePattern)
	fmt.Fprintf(&b, "/** The shortest password the server takes. */\n")
	fmt.Fprintf(&b, "export const MIN_PASSWORD_LENGTH = %d;\n\n", family.MinPasswordRunes)
	b.WriteString("/** Which kinds of paper a hand entry of each type may name (decision Р-17); a type not listed may name any. */\n")
	b.WriteString("export const KINDS_FOR: Partial<Record<OperationType, readonly InstrumentType[]>> = {\n")
	kinds := operation.KindsFor()
	types := make([]string, 0, len(kinds))
	for t := range kinds {
		types = append(types, string(t))
	}
	slices.Sort(types)
	for _, t := range types {
		quoted := make([]string, 0, len(kinds[operation.Type(t)]))
		for _, k := range kinds[operation.Type(t)] {
			quoted = append(quoted, strconv.Quote(string(k)))
		}
		fmt.Fprintf(&b, "  %s: [%s],\n", t, strings.Join(quoted, ", "))
	}
	b.WriteString("};\n")
	return b.Bytes()
}

// grouped writes n with underscores between thousands, as the web code does.
func grouped(n int64) string {
	s := strconv.FormatInt(n, 10)
	var parts []string
	for len(s) > 3 {
		parts = append([]string{s[len(s)-3:]}, parts...)
		s = s[:len(s)-3]
	}
	return strings.Join(append([]string{s}, parts...), "_")
}
