// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apitypes

import (
	"time"

	"github.com/oapi-codegen/nullable"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AccountStatus.
const (
	Active   AccountStatus = "active"
	Archived AccountStatus = "archived"
)

// Valid indicates whether the value is a known member of the AccountStatus enum.
func (e AccountStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Archived:
		return true
	default:
		return false
	}
}

// Defines values for AccountType.
const (
	AccountTypeBrokerage  AccountType = "brokerage"
	AccountTypeCash       AccountType = "cash"
	AccountTypeChecking   AccountType = "checking"
	AccountTypeCreditCard AccountType = "credit_card"
	AccountTypeDeposit    AccountType = "deposit"
	AccountTypeLoan       AccountType = "loan"
	AccountTypeSavings    AccountType = "savings"
)

// Valid indicates whether the value is a known member of the AccountType enum.
func (e AccountType) Valid() bool {
	switch e {
	case AccountTypeBrokerage:
		return true
	case AccountTypeCash:
		return true
	case AccountTypeChecking:
		return true
	case AccountTypeCreditCard:
		return true
	case AccountTypeDeposit:
		return true
	case AccountTypeLoan:
		return true
	case AccountTypeSavings:
		return true
	default:
		return false
	}
}

// Defines values for InstrumentType.
const (
	Bond     InstrumentType = "bond"
	Crypto   InstrumentType = "crypto"
	Currency InstrumentType = "currency"
	Custom   InstrumentType = "custom"
	Etf      InstrumentType = "etf"
	Metal    InstrumentType = "metal"
	Share    InstrumentType = "share"
)

// Valid indicates whether the value is a known member of the InstrumentType enum.
func (e InstrumentType) Valid() bool {
	switch e {
	case Bond:
		return true
	case Crypto:
		return true
	case Currency:
		return true
	case Custom:
		return true
	case Etf:
		return true
	case Metal:
		return true
	case Share:
		return true
	default:
		return false
	}
}

// Defines values for OperationType.
const (
	OperationTypeAmortization OperationType = "amortization"
	OperationTypeBuy          OperationType = "buy"
	OperationTypeConversion   OperationType = "conversion"
	OperationTypeCoupon       OperationType = "coupon"
	OperationTypeDeposit      OperationType = "deposit"
	OperationTypeDividend     OperationType = "dividend"
	OperationTypeFee          OperationType = "fee"
	OperationTypeInterest     OperationType = "interest"
	OperationTypeSell         OperationType = "sell"
	OperationTypeSplit        OperationType = "split"
	OperationTypeTax          OperationType = "tax"
	OperationTypeTransferIn   OperationType = "transfer_in"
	OperationTypeTransferOut  OperationType = "transfer_out"
	OperationTypeWithdrawal   OperationType = "withdrawal"
)

// Valid indicates whether the value is a known member of the OperationType enum.
func (e OperationType) Valid() bool {
	switch e {
	case OperationTypeAmortization:
		return true
	case OperationTypeBuy:
		return true
	case OperationTypeConversion:
		return true
	case OperationTypeCoupon:
		return true
	case OperationTypeDeposit:
		return true
	case OperationTypeDividend:
		return true
	case OperationTypeFee:
		return true
	case OperationTypeInterest:
		return true
	case OperationTypeSell:
		return true
	case OperationTypeSplit:
		return true
	case OperationTypeTax:
		return true
	case OperationTypeTransferIn:
		return true
	case OperationTypeTransferOut:
		return true
	case OperationTypeWithdrawal:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	Editor Role = "editor"
	Owner  Role = "owner"
	Viewer Role = "viewer"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case Editor:
		return true
	case Owner:
		return true
	case Viewer:
		return true
	default:
		return false
	}
}

// AccountStatus defines model for AccountStatus.
type AccountStatus string

// AccountType defines model for AccountType.
type AccountType string

// AccountWithBalance defines model for AccountWithBalance.
type AccountWithBalance struct {
	Balance *BalancePoint `json:"balance,omitempty"`

	// BalanceInBase Account's balance converted into the space's base currency at today's fx rate. Null when the account has no balance, its currency already equals base_currency (nothing to convert), or no fx rate could be resolved.
	BalanceInBase nullable.Nullable[MoneyInBase]        `json:"balance_in_base,omitempty"`
	CreatedAt     time.Time                             `json:"created_at"`
	Currency      string                                `json:"currency"`
	Id            openapi_types.UUID                    `json:"id"`
	Institution   string                                `json:"institution"`
	Name          string                                `json:"name"`
	OwnerUserId   nullable.Nullable[openapi_types.UUID] `json:"owner_user_id,omitempty"`
	Status        AccountStatus                         `json:"status"`
	Type          AccountType                           `json:"type"`
}

// BalancePoint defines model for BalancePoint.
type BalancePoint struct {
	AmountMinor int64 `json:"amount_minor"`

	// AsOf Date YYYY-MM-DD
	AsOf string `json:"as_of"`
}

// CreateAccountRequest defines model for CreateAccountRequest.
type CreateAccountRequest struct {
	// Currency ISO-4217, e.g. RUB
	Currency    string                                `json:"currency"`
	Institution *string                               `json:"institution,omitempty"`
	Name        string                                `json:"name"`
	OwnerUserId nullable.Nullable[openapi_types.UUID] `json:"owner_user_id,omitempty"`
	Type        AccountType                           `json:"type"`
}

// CreateInstrumentRequest defines model for CreateInstrumentRequest.
type CreateInstrumentRequest struct {
	Currency       string                    `json:"currency"`
	FaceCurrency   nullable.Nullable[string] `json:"face_currency,omitempty"`
	FaceValueMinor nullable.Nullable[int64]  `json:"face_value_minor,omitempty"`
	Figi           *string                   `json:"figi,omitempty"`
	Isin           *string                   `json:"isin,omitempty"`
	Name           string                    `json:"name"`
	Ticker         *string                   `json:"ticker,omitempty"`
	Type           InstrumentType            `json:"type"`
}

// CreateMemberRequest defines model for CreateMemberRequest.
type CreateMemberRequest struct {
	DisplayName string `json:"display_name"`
	Password    string `json:"password"`
	Role        Role   `json:"role"`
	Username    string `json:"username"`
}

// CreateOperationRequest defines model for CreateOperationRequest.
type CreateOperationRequest struct {
	AccountId    openapi_types.UUID                    `json:"account_id"`
	AmountMinor  int64                                 `json:"amount_minor"`
	Currency     string                                `json:"currency"`
	FeeMinor     *int64                                `json:"fee_minor,omitempty"`
	InstrumentId nullable.Nullable[openapi_types.UUID] `json:"instrument_id,omitempty"`
	Note         *string                               `json:"note,omitempty"`

	// OccurredOn Date YYYY-MM-DD
	OccurredOn string `json:"occurred_on"`

	// Price Decimal as string
	Price nullable.Nullable[string] `json:"price,omitempty"`

	// Quantity Decimal as string
	Quantity  nullable.Nullable[string] `json:"quantity,omitempty"`
	SettledOn nullable.Nullable[string] `json:"settled_on,omitempty"`

	// SplitRatio Decimal as string
	SplitRatio nullable.Nullable[string] `json:"split_ratio,omitempty"`
	Type       OperationType             `json:"type"`
}

// CurrencyTotal defines model for CurrencyTotal.
type CurrencyTotal struct {
	AssetsMinor int64  `json:"assets_minor"`
	Currency    string `json:"currency"`

	// LiabilitiesMinor Negative or zero
	LiabilitiesMinor int64 `json:"liabilities_minor"`
	NetMinor         int64 `json:"net_minor"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// Instrument defines model for Instrument.
type Instrument struct {
	Currency       string                    `json:"currency"`
	FaceCurrency   nullable.Nullable[string] `json:"face_currency,omitempty"`
	FaceValueMinor nullable.Nullable[int64]  `json:"face_value_minor,omitempty"`
	Figi           string                    `json:"figi"`
	Frozen         bool                      `json:"frozen"`
	Id             openapi_types.UUID        `json:"id"`
	Isin           string                    `json:"isin"`
	Name           string                    `json:"name"`
	Ticker         string                    `json:"ticker"`
	Type           InstrumentType            `json:"type"`
}

// InstrumentType defines model for InstrumentType.
type InstrumentType string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// MemberInfo defines model for MemberInfo.
type MemberInfo struct {
	DisplayName string             `json:"display_name"`
	Id          openapi_types.UUID `json:"id"`
	Role        Role               `json:"role"`
	Username    string             `json:"username"`
}

// MoneyInBase defines model for MoneyInBase.
type MoneyInBase struct {
	// AmountMinor Amount in the base currency's minor units
	AmountMinor int64 `json:"amount_minor"`

	// Currency The space's base currency (ISO-4217), same as Summary.base_currency
	Currency string `json:"currency"`

	// RateOn Date YYYY-MM-DD of the fx rate actually used for this conversion
	RateOn string `json:"rate_on"`
}

// Operation defines model for Operation.
type Operation struct {
	AccountId   openapi_types.UUID `json:"account_id"`
	AmountMinor int64              `json:"amount_minor"`
	CreatedAt   time.Time          `json:"created_at"`
	Currency    string             `json:"currency"`
	FeeMinor    int64              `json:"fee_minor"`
	Id          openapi_types.UUID `json:"id"`

	// InBase amount_minor and fee_minor converted into the space's base currency at the fx rate in effect on occurred_on — the rate of the day the operation happened, NOT today's. This is the deliberate difference from AccountWithBalance.balance_in_base and Position.in_base, which answer "what is this worth now"; the journal answers "what did this cost then". Each amount is converted and rounded independently. Null when `currency` already equals the base currency (nothing to convert), or when no fx rate could be resolved for occurred_on nor any earlier date — a partially converted operation is never published. Computed only for the journal listing (GET /accounts/{accountId}/operations); create and transfer responses omit the field entirely, since those return an operation the client just submitted rather than a journal to read. An absent field and an explicit null mean the same thing to a reader: there is nothing converted to show.
	InBase       nullable.Nullable[OperationInBase]    `json:"in_base,omitempty"`
	InstrumentId nullable.Nullable[openapi_types.UUID] `json:"instrument_id,omitempty"`
	Note         string                                `json:"note"`

	// OccurredOn Date YYYY-MM-DD
	OccurredOn string `json:"occurred_on"`

	// Price Decimal as string
	Price nullable.Nullable[string] `json:"price,omitempty"`

	// Quantity Decimal as string
	Quantity nullable.Nullable[string] `json:"quantity,omitempty"`

	// SettledOn Date YYYY-MM-DD
	SettledOn nullable.Nullable[string] `json:"settled_on,omitempty"`
	Source    string                    `json:"source"`

	// SplitRatio Decimal as string
	SplitRatio      nullable.Nullable[string]             `json:"split_ratio,omitempty"`
	TransferGroupId nullable.Nullable[openapi_types.UUID] `json:"transfer_group_id,omitempty"`
	Type            OperationType                         `json:"type"`
}

// OperationInBase defines model for OperationInBase.
type OperationInBase struct {
	// AmountMinor Operation.amount_minor converted into currency. The sign is preserved — a buy stays negative — and rounding is half-away-from-zero, so converting never shrinks the magnitude of an outflow
	AmountMinor int64 `json:"amount_minor"`

	// Currency The space's base currency (ISO-4217), same as Summary.base_currency
	Currency string `json:"currency"`

	// FeeMinor Operation.fee_minor converted into currency, rounded independently of amount_minor: the two are separate figures, not terms of one total
	FeeMinor int64 `json:"fee_minor"`

	// RateOn Date YYYY-MM-DD of the fx rate ACTUALLY used, which is occurred_on itself or the nearest earlier date that has a rate (weekend, holiday, provider gap) — never today's date. For a 2019 operation this is a 2019 date; that is what makes this a historical conversion rather than a current valuation
	RateOn string `json:"rate_on"`
}

// OperationType defines model for OperationType.
type OperationType string

// Position defines model for Position.
type Position struct {
	CostMinor int64  `json:"cost_minor"`
	Currency  string `json:"currency"`
	FeesMinor int64  `json:"fees_minor"`

	// InBase cost_minor/market_value_minor/unrealized_pnl_minor/income_minor converted from the position's own `currency` into the space's base currency at today's fx rate, each amount rounded independently (not derived from one another). Null when `currency` already equals the base currency (nothing to convert) or no fx rate could be resolved for the pair — a partially converted position is never published. Inside the object, market_value_minor and unrealized_pnl_minor can still be null on their own when the valuation isn't in the position's currency (see their descriptions). fees_minor and realized_pnl_minor are intentionally not carried into this object (owner feedback).
	InBase      nullable.Nullable[PositionInBase] `json:"in_base,omitempty"`
	IncomeMinor int64                             `json:"income_minor"`
	Instrument  Instrument                        `json:"instrument"`

	// MarketValueCurrency Currency of market_value_minor. Equal to `currency` (the position's own currency) whenever a conversion happened; otherwise the raw valuation currency (the quote's currency for share/etf, the instrument's face_currency for bond). Null exactly when market_value_minor is null.
	MarketValueCurrency nullable.Nullable[string] `json:"market_value_currency,omitempty"`

	// MarketValueMinor Market value in market_value_currency; always the same currency as the position's own `currency` when a conversion rate was available, so it's directly comparable to cost_minor. For a bond whose raw valuation is in the face value's currency (not the quote's) and that currency differs from the position's, this is the value converted into the position's currency at today's fx rate; if no rate is available it falls back to the raw (unconverted) value. Null if no usable quote.
	MarketValueMinor nullable.Nullable[int64] `json:"market_value_minor,omitempty"`

	// MarketValueSourceCurrency Set only when market_value_minor was converted from a different currency (see market_value_minor): the original, unconverted valuation currency (e.g. a bond's face_currency). Null when no conversion happened, including when one was needed but no fx rate was available.
	MarketValueSourceCurrency nullable.Nullable[string] `json:"market_value_source_currency,omitempty"`

	// MarketValueSourceMinor Set only when market_value_minor was converted from a different currency: the original, unconverted valuation amount in market_value_source_currency, kept for transparency (e.g. shown in a tooltip). Null when no conversion happened.
	MarketValueSourceMinor nullable.Nullable[int64] `json:"market_value_source_minor,omitempty"`

	// Price Decimal as string; latest quote price used for the valuation
	Price nullable.Nullable[string] `json:"price,omitempty"`

	// PriceOn Date YYYY-MM-DD of the quote used for the valuation
	PriceOn nullable.Nullable[string] `json:"price_on,omitempty"`

	// Quantity Decimal as string
	Quantity         string `json:"quantity"`
	RealizedPnlMinor int64  `json:"realized_pnl_minor"`

	// UnrealizedPnlMinor market_value_minor minus cost_minor, i.e. the position's unrealized profit or loss; both are already in the same currency (market_value_minor is converted into the position's currency when needed, see above), so this is a plain integer subtraction. Null when there is no market_value_minor, or when market_value_currency still differs from currency (a conversion was needed but no fx rate was available).
	UnrealizedPnlMinor nullable.Nullable[int64] `json:"unrealized_pnl_minor,omitempty"`
}

// PositionInBase defines model for PositionInBase.
type PositionInBase struct {
	// CostMinor Position.cost_minor converted into currency
	CostMinor int64 `json:"cost_minor"`

	// Currency The space's base currency (ISO-4217), same as Summary.base_currency
	Currency string `json:"currency"`

	// IncomeMinor Position.income_minor converted into currency
	IncomeMinor int64 `json:"income_minor"`

	// MarketValueMinor Position.market_value_minor converted into currency, never fabricated. Null when Position.market_value_minor itself is null (no usable quote), AND null whenever market_value_currency differs from the position's own currency: the single rate used for this object converts the position's currency into the base currency, so a valuation still denominated in some other currency (a bond's face_currency, when no rate could bring it into the position's currency) cannot be expressed here — publishing it multiplied by the wrong pair's rate would be a silently wrong number
	MarketValueMinor nullable.Nullable[int64] `json:"market_value_minor,omitempty"`

	// RateOn Date YYYY-MM-DD of the fx rate actually used for this conversion
	RateOn string `json:"rate_on"`

	// UnrealizedPnlMinor Position.unrealized_pnl_minor converted into currency; null exactly when Position.unrealized_pnl_minor itself is null, which covers every case where market_value_minor above is null — the P&L is derived from the valuation and cannot outlive it
	UnrealizedPnlMinor nullable.Nullable[int64] `json:"unrealized_pnl_minor,omitempty"`
}

// PositionsResponse defines model for PositionsResponse.
type PositionsResponse struct {
	Positions []Position `json:"positions"`
}

// Role defines model for Role.
type Role string

// SessionInfo defines model for SessionInfo.
type SessionInfo struct {
	// BaseCurrency ISO-4217, e.g. RUB
	BaseCurrency string             `json:"base_currency"`
	Role         Role               `json:"role"`
	SpaceId      openapi_types.UUID `json:"space_id"`
	SpaceName    string             `json:"space_name"`
	User         UserInfo           `json:"user"`
}

// SetBalanceRequest defines model for SetBalanceRequest.
type SetBalanceRequest struct {
	AmountMinor int64 `json:"amount_minor"`

	// AsOf Date YYYY-MM-DD
	AsOf string `json:"as_of"`
}

// SetupRequest defines model for SetupRequest.
type SetupRequest struct {
	DisplayName string `json:"display_name"`
	Password    string `json:"password"`
	SpaceName   string `json:"space_name"`
	Username    string `json:"username"`
}

// SetupStatus defines model for SetupStatus.
type SetupStatus struct {
	SetupNeeded bool `json:"setup_needed"`
}

// Summary defines model for Summary.
type Summary struct {
	// BaseCurrency ISO-4217, from the space; e.g. RUB
	BaseCurrency string `json:"base_currency"`

	// RatesOn Oldest FX rate date used for the conversion; null if nothing was converted
	RatesOn nullable.Nullable[string] `json:"rates_on,omitempty"`

	// TotalInBaseMinor Sum of totals[].net_minor converted using the latest FX rate on or before today; null only if none of the currencies could be converted
	TotalInBaseMinor nullable.Nullable[int64] `json:"total_in_base_minor,omitempty"`
	Totals           []CurrencyTotal          `json:"totals"`

	// Unconverted Currencies from totals that had no fx rate available and were excluded from total_in_base_minor; empty if all converted
	Unconverted []string `json:"unconverted"`
}

// TransferRequest defines model for TransferRequest.
type TransferRequest struct {
	// CostMinor Cost basis override; default is FIFO carryover from the source account
	CostMinor     nullable.Nullable[int64] `json:"cost_minor,omitempty"`
	FromAccountId openapi_types.UUID       `json:"from_account_id"`
	InstrumentId  openapi_types.UUID       `json:"instrument_id"`
	Note          *string                  `json:"note,omitempty"`

	// OccurredOn Date YYYY-MM-DD
	OccurredOn string `json:"occurred_on"`

	// Quantity Decimal as string
	Quantity    string             `json:"quantity"`
	ToAccountId openapi_types.UUID `json:"to_account_id"`
}

// TransferResponse defines model for TransferResponse.
type TransferResponse struct {
	In  Operation `json:"in"`
	Out Operation `json:"out"`
}

// UpdateAccountRequest defines model for UpdateAccountRequest.
type UpdateAccountRequest struct {
	Institution *string                               `json:"institution,omitempty"`
	Name        *string                               `json:"name,omitempty"`
	OwnerUserId nullable.Nullable[openapi_types.UUID] `json:"owner_user_id,omitempty"`
	Status      *AccountStatus                        `json:"status,omitempty"`
}

// UpdateInstrumentRequest defines model for UpdateInstrumentRequest.
type UpdateInstrumentRequest struct {
	FaceCurrency   nullable.Nullable[string] `json:"face_currency,omitempty"`
	FaceValueMinor nullable.Nullable[int64]  `json:"face_value_minor,omitempty"`
	Figi           *string                   `json:"figi,omitempty"`
	Frozen         *bool                     `json:"frozen,omitempty"`
	Isin           *string                   `json:"isin,omitempty"`
	Name           *string                   `json:"name,omitempty"`
	Ticker         *string                   `json:"ticker,omitempty"`
}

// UpdateMemberRequest defines model for UpdateMemberRequest.
type UpdateMemberRequest struct {
	Role Role `json:"role"`
}

// UpdateSpaceRequest defines model for UpdateSpaceRequest.
type UpdateSpaceRequest struct {
	// BaseCurrency ISO-4217 uppercase, e.g. RUB
	BaseCurrency string `json:"base_currency"`
}

// UserInfo defines model for UserInfo.
type UserInfo struct {
	DisplayName string             `json:"display_name"`
	Id          openapi_types.UUID `json:"id"`
	Username    string             `json:"username"`
}

// Error defines model for Error.
type Error = ErrorResponse

// ListAccountOperationsParams defines parameters for ListAccountOperations.
type ListAccountOperationsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// SearchInstrumentsParams defines parameters for SearchInstruments.
type SearchInstrumentsParams struct {
	Query *string `form:"query,omitempty" json:"query,omitempty"`
	Limit *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody = CreateAccountRequest

// UpdateAccountJSONRequestBody defines body for UpdateAccount for application/json ContentType.
type UpdateAccountJSONRequestBody = UpdateAccountRequest

// SetAccountBalanceJSONRequestBody defines body for SetAccountBalance for application/json ContentType.
type SetAccountBalanceJSONRequestBody = SetBalanceRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreateInstrumentJSONRequestBody defines body for CreateInstrument for application/json ContentType.
type CreateInstrumentJSONRequestBody = CreateInstrumentRequest

// UpdateInstrumentJSONRequestBody defines body for UpdateInstrument for application/json ContentType.
type UpdateInstrumentJSONRequestBody = UpdateInstrumentRequest

// CreateMemberJSONRequestBody defines body for CreateMember for application/json ContentType.
type CreateMemberJSONRequestBody = CreateMemberRequest

// UpdateMemberJSONRequestBody defines body for UpdateMember for application/json ContentType.
type UpdateMemberJSONRequestBody = UpdateMemberRequest

// CreateOperationJSONRequestBody defines body for CreateOperation for application/json ContentType.
type CreateOperationJSONRequestBody = CreateOperationRequest

// CreateTransferJSONRequestBody defines body for CreateTransfer for application/json ContentType.
type CreateTransferJSONRequestBody = TransferRequest

// PerformSetupJSONRequestBody defines body for PerformSetup for application/json ContentType.
type PerformSetupJSONRequestBody = SetupRequest

// UpdateSpaceJSONRequestBody defines body for UpdateSpace for application/json ContentType.
type UpdateSpaceJSONRequestBody = UpdateSpaceRequest
